/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="addCustomerForm"
 */
public class AddCustomerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** customerBirtyday property */
	private String customerBirtyday;

	/** customerAddress property */
	private String customerAddress;

	/** customerSex property */
	private String customerSex;

	/** customerName property */
	private String customerName;

	/** idNumber property */
	private String idNumber;

	/** idType property */
	private String idType;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the customerBirtyday.
	 * @return String
	 */
	public String getCustomerBirtyday() {
		return customerBirtyday;
	}

	/** 
	 * Set the customerBirtyday.
	 * @param customerBirtyday The customerBirtyday to set
	 */
	public void setCustomerBirtyday(String customerBirtyday) {
		this.customerBirtyday = customerBirtyday;
	}

	/** 
	 * Returns the customerAddress.
	 * @return String
	 */
	public String getCustomerAddress() {
		return customerAddress;
	}

	/** 
	 * Set the customerAddress.
	 * @param customerAddress The customerAddress to set
	 */
	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	/** 
	 * Returns the customerSex.
	 * @return String
	 */
	public String getCustomerSex() {
		return customerSex;
	}

	/** 
	 * Set the customerSex.
	 * @param customerSex The customerSex to set
	 */
	public void setCustomerSex(String customerSex) {
		this.customerSex = customerSex;
	}

	/** 
	 * Returns the customerName.
	 * @return String
	 */
	public String getCustomerName() {
		return customerName;
	}

	/** 
	 * Set the customerName.
	 * @param customerName The customerName to set
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/** 
	 * Returns the idNumber.
	 * @return String
	 */
	public String getIdNumber() {
		return idNumber;
	}

	/** 
	 * Set the idNumber.
	 * @param idNumber The idNumber to set
	 */
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	/** 
	 * Returns the idType.
	 * @return String
	 */
	public String getIdType() {
		return idType;
	}

	/** 
	 * Set the idType.
	 * @param idType The idType to set
	 */
	public void setIdType(String idType) {
		this.idType = idType;
	}
}