/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="addOperatorForm"
 */
public class AddOperatorForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** operatorName property */
	private String operatorName;

	/** operatorId property */
	private String operatorId;

	/** isAdmin property */
	private String isAdmin;

	/** operatorPwd property */
	private String operatorPwd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the operatorName.
	 * @return String
	 */
	public String getOperatorName() {
		return operatorName;
	}

	/** 
	 * Set the operatorName.
	 * @param operatorName The operatorName to set
	 */
	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	/** 
	 * Returns the operatorId.
	 * @return String
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/** 
	 * Set the operatorId.
	 * @param operatorId The operatorId to set
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/** 
	 * Returns the isAdmin.
	 * @return String
	 */
	public String getIsAdmin() {
		return isAdmin;
	}

	/** 
	 * Set the isAdmin.
	 * @param isAdmin The isAdmin to set
	 */
	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}

	/** 
	 * Returns the operatorPwd.
	 * @return String
	 */
	public String getOperatorPwd() {
		return operatorPwd;
	}

	/** 
	 * Set the operatorPwd.
	 * @param operatorPwd The operatorPwd to set
	 */
	public void setOperatorPwd(String operatorPwd) {
		this.operatorPwd = operatorPwd;
	}
}