/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="editChargeForm"
 */
public class EditChargeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** charge property */
	private String charge;

	/** chargeCode property */
	private String chargeCode;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the charge.
	 * @return String
	 */
	public String getCharge() {
		return charge;
	}

	/** 
	 * Set the charge.
	 * @param charge The charge to set
	 */
	public void setCharge(String charge) {
		this.charge = charge;
	}

	/** 
	 * Returns the chargeCode.
	 * @return String
	 */
	public String getChargeCode() {
		return chargeCode;
	}

	/** 
	 * Set the chargeCode.
	 * @param chargeCode The chargeCode to set
	 */
	public void setChargeCode(String chargeCode) {
		this.chargeCode = chargeCode;
	}
}