/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="editChargeRuleForm"
 */
public class EditChargeRuleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** rule property */
	private String rule;

	/** iterm property */
	private String iterm;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the rule.
	 * @return String
	 */
	public String getRule() {
		return rule;
	}

	/** 
	 * Set the rule.
	 * @param rule The rule to set
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}

	/** 
	 * Returns the iterm.
	 * @return String
	 */
	public String getIterm() {
		return iterm;
	}

	/** 
	 * Set the iterm.
	 * @param iterm The iterm to set
	 */
	public void setIterm(String iterm) {
		this.iterm = iterm;
	}
}