/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-02-2006
 * 
 * XDoclet definition:
 * @struts.form name="resourceForm"
 */
public class ResourceForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** startMobile property */
	private String startMobile;

	/** nbtype property */
	private String nbtype;

	/** endMobile property */
	private String endMobile;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the startMobile.
	 * @return String
	 */
	public String getStartMobile() {
		return startMobile;
	}

	/** 
	 * Set the startMobile.
	 * @param startMobile The startMobile to set
	 */
	public void setStartMobile(String startMobile) {
		this.startMobile = startMobile;
	}

	/** 
	 * Returns the nbtype.
	 * @return String
	 */
	public String getNbtype() {
		return nbtype;
	}

	/** 
	 * Set the nbtype.
	 * @param nbtype The nbtype to set
	 */
	public void setNbtype(String nbtype) {
		this.nbtype = nbtype;
	}

	/** 
	 * Returns the endMobile.
	 * @return String
	 */
	public String getEndMobile() {
		return endMobile;
	}

	/** 
	 * Set the endMobile.
	 * @param endMobile The endMobile to set
	 */
	public void setEndMobile(String endMobile) {
		this.endMobile = endMobile;
	}
}