package po;



/**
 * AbstractTuser generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTuser  implements java.io.Serializable {


    // Fields    

     private Long userId;
     private Tmobiles tmobiles;
     private Tcustomer tcustomer;
     private String roamingStatus;
     private String comLevel;


    // Constructors

    /** default constructor */
    public AbstractTuser() {
    }

    
    /** full constructor */
    public AbstractTuser(Tmobiles tmobiles, Tcustomer tcustomer, String roamingStatus, String comLevel) {
        this.tmobiles = tmobiles;
        this.tcustomer = tcustomer;
        this.roamingStatus = roamingStatus;
        this.comLevel = comLevel;
    }

   
    // Property accessors

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Tmobiles getTmobiles() {
        return this.tmobiles;
    }
    
    public void setTmobiles(Tmobiles tmobiles) {
        this.tmobiles = tmobiles;
    }

    public Tcustomer getTcustomer() {
        return this.tcustomer;
    }
    
    public void setTcustomer(Tcustomer tcustomer) {
        this.tcustomer = tcustomer;
    }

    public String getRoamingStatus() {
        return this.roamingStatus;
    }
    
    public void setRoamingStatus(String roamingStatus) {
        this.roamingStatus = roamingStatus;
    }

    public String getComLevel() {
        return this.comLevel;
    }
    
    public void setComLevel(String comLevel) {
        this.comLevel = comLevel;
    }
   








}