package po;



/**
 * AbstractTchargeRule generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTchargeRule  implements java.io.Serializable {


    // Fields    

     private TchargeRuleId id;
     private Tcharge tcharge;


    // Constructors

    /** default constructor */
    public AbstractTchargeRule() {
    }

	/** minimal constructor */
    public AbstractTchargeRule(TchargeRuleId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractTchargeRule(TchargeRuleId id, Tcharge tcharge) {
        this.id = id;
        this.tcharge = tcharge;
    }

   
    // Property accessors

    public TchargeRuleId getId() {
        return this.id;
    }
    
    public void setId(TchargeRuleId id) {
        this.id = id;
    }

    public Tcharge getTcharge() {
        return this.tcharge;
    }
    
    public void setTcharge(Tcharge tcharge) {
        this.tcharge = tcharge;
    }
   








}