package po;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTmobiles generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTmobiles  implements java.io.Serializable {


    // Fields    

     private String mobileNumber;
     private String mobileType;
     private String cardNumber;
     private String isAvailable;
     private Set tusers = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTmobiles() {
    }

	/** minimal constructor */
    public AbstractTmobiles(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    
    /** full constructor */
    public AbstractTmobiles(String mobileNumber, String mobileType, String cardNumber, String isAvailable, Set tusers) {
        this.mobileNumber = mobileNumber;
        this.mobileType = mobileType;
        this.cardNumber = cardNumber;
        this.isAvailable = isAvailable;
        this.tusers = tusers;
    }

   
    // Property accessors

    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getMobileType() {
        return this.mobileType;
    }
    
    public void setMobileType(String mobileType) {
        this.mobileType = mobileType;
    }

    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getIsAvailable() {
        return this.isAvailable;
    }
    
    public void setIsAvailable(String isAvailable) {
        this.isAvailable = isAvailable;
    }

    public Set getTusers() {
        return this.tusers;
    }
    
    public void setTusers(Set tusers) {
        this.tusers = tusers;
    }
   








}