package po;



/**
 * AbstractTchargeRuleId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTchargeRuleId  implements java.io.Serializable {


    // Fields    

     private String funcId;
     private Tcharge tcharge;
     private String funcName;


    // Constructors

    /** default constructor */
    public AbstractTchargeRuleId() {
    }

    
    /** full constructor */
    public AbstractTchargeRuleId(String funcId, Tcharge tcharge, String funcName) {
        this.funcId = funcId;
        this.tcharge = tcharge;
        this.funcName = funcName;
    }

   
    // Property accessors

    public String getFuncId() {
        return this.funcId;
    }
    
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }

    public Tcharge getTcharge() {
        return this.tcharge;
    }
    
    public void setTcharge(Tcharge tcharge) {
        this.tcharge = tcharge;
    }

    public String getFuncName() {
        return this.funcName;
    }
    
    public void setFuncName(String funcName) {
        this.funcName = funcName;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractTchargeRuleId) ) return false;
		 AbstractTchargeRuleId castOther = ( AbstractTchargeRuleId ) other; 
         
		 return ( (this.getFuncId()==castOther.getFuncId()) || ( this.getFuncId()!=null && castOther.getFuncId()!=null && this.getFuncId().equals(castOther.getFuncId()) ) )
 && ( (this.getTcharge()==castOther.getTcharge()) || ( this.getTcharge()!=null && castOther.getTcharge()!=null && this.getTcharge().equals(castOther.getTcharge()) ) )
 && ( (this.getFuncName()==castOther.getFuncName()) || ( this.getFuncName()!=null && castOther.getFuncName()!=null && this.getFuncName().equals(castOther.getFuncName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFuncId() == null ? 0 : this.getFuncId().hashCode() );
         result = 37 * result + ( getTcharge() == null ? 0 : this.getTcharge().hashCode() );
         result = 37 * result + ( getFuncName() == null ? 0 : this.getFuncName().hashCode() );
         return result;
   }   





}