package po;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTcustomer generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTcustomer  implements java.io.Serializable {


    // Fields    

     private Long customerId;
     private String idType;
     private String idNumber;
     private String customerName;
     private String customerBirtyday;
     private String customerSex;
     private String customerAddress;
     private Set tusers = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTcustomer() {
    }

    
    /** full constructor */
    public AbstractTcustomer(String idType, String idNumber, String customerName, String customerBirtyday, String customerSex, String customerAddress, Set tusers) {
        this.idType = idType;
        this.idNumber = idNumber;
        this.customerName = customerName;
        this.customerBirtyday = customerBirtyday;
        this.customerSex = customerSex;
        this.customerAddress = customerAddress;
        this.tusers = tusers;
    }

   
    // Property accessors

    public Long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getIdType() {
        return this.idType;
    }
    
    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerBirtyday() {
        return this.customerBirtyday;
    }
    
    public void setCustomerBirtyday(String customerBirtyday) {
        this.customerBirtyday = customerBirtyday;
    }

    public String getCustomerSex() {
        return this.customerSex;
    }
    
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex;
    }

    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    public Set getTusers() {
        return this.tusers;
    }
    
    public void setTusers(Set tusers) {
        this.tusers = tusers;
    }
   








}