package po;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTcharge generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTcharge  implements java.io.Serializable {


    // Fields    

     private String chargeCode;
     private String chargeName;
     private Double charge;
     private Set tchargeRules = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTcharge() {
    }

    
    /** full constructor */
    public AbstractTcharge(String chargeName, Double charge, Set tchargeRules) {
        this.chargeName = chargeName;
        this.charge = charge;
        this.tchargeRules = tchargeRules;
    }

   
    // Property accessors

    public String getChargeCode() {
        return this.chargeCode;
    }
    
    public void setChargeCode(String chargeCode) {
        this.chargeCode = chargeCode;
    }

    public String getChargeName() {
        return this.chargeName;
    }
    
    public void setChargeName(String chargeName) {
        this.chargeName = chargeName;
    }

    public Double getCharge() {
        return this.charge;
    }
    
    public void setCharge(Double charge) {
        this.charge = charge;
    }

    public Set getTchargeRules() {
        return this.tchargeRules;
    }
    
    public void setTchargeRules(Set tchargeRules) {
        this.tchargeRules = tchargeRules;
    }
   








}