package po;
// Generated by MyEclipse - Hibernate Tools



/**
 * TchargeRule generated by MyEclipse - Hibernate Tools
 */
public class TchargeRule extends AbstractTchargeRule implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TchargeRule() {
    }

	/** minimal constructor */
    public TchargeRule(TchargeRuleId id) {
        super(id);        
    }
    
    /** full constructor */
    public TchargeRule(TchargeRuleId id, Tcharge tcharge) {
        super(id, tcharge);        
    }
   
}
