package po;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Tcharge generated by MyEclipse - Hibernate Tools
 */
public class Tcharge extends AbstractTcharge implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Tcharge() {
    }

    
    /** full constructor */
    public Tcharge(String chargeName, Double charge, Set tchargeRules) {
        super(chargeName, charge, tchargeRules);        
    }
   
}
