package po;
// Generated by MyEclipse - Hibernate Tools



/**
 * TchargeRuleId generated by MyEclipse - Hibernate Tools
 */
public class TchargeRuleId extends AbstractTchargeRuleId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TchargeRuleId() {
    }

    
    /** full constructor */
    public TchargeRuleId(String funcId, Tcharge tcharge, String funcName) {
        super(funcId, tcharge, funcName);        
    }
   
}
