package po;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Tcustomer generated by MyEclipse - Hibernate Tools
 */
public class Tcustomer extends AbstractTcustomer implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Tcustomer() {
    }

    
    /** full constructor */
    public Tcustomer(String idType, String idNumber, String customerName, String customerBirtyday, String customerSex, String customerAddress, Set tusers) {
        super(idType, idNumber, customerName, customerBirtyday, customerSex, customerAddress, tusers);        
    }
   
}
