package po;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Tmobiles generated by MyEclipse - Hibernate Tools
 */
public class Tmobiles extends AbstractTmobiles implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Tmobiles() {
    }

    
    /** full constructor */
    public Tmobiles(String mobileType, String cardNumber, String isAvailable, Set tusers) {
        super(mobileType, cardNumber, isAvailable, isAvailable, tusers);        
    }
   
}
