package po;
// Generated by MyEclipse - Hibernate Tools



/**
 * Toperator generated by MyEclipse - Hibernate Tools
 */
public class Toperator extends AbstractToperator implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Toperator() {
    }

    
    /** full constructor */
    public Toperator(String operatorName, String operatorPwd, Long isAdmin) {
        super(isAdmin, operatorName, operatorPwd, isAdmin);        
    }
   
}
