package po;
// Generated by MyEclipse - Hibernate Tools



/**
 * Tuser generated by MyEclipse - Hibernate Tools
 */
public class Tuser extends AbstractTuser implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Tuser() {
    }

    
    /** full constructor */
    public Tuser(Tmobiles tmobiles, Tcustomer tcustomer, String roamingStatus, String comLevel) {
        super(tmobiles, tcustomer, roamingStatus, comLevel);        
    }
   
}
