/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.FileSystemXmlApplicationContext;

import business.IAdminOperator;

import po.Toperator;
import struts.form.AddOperatorForm;

/** 
 * 功能:增加操作员
 * 作者:赵昌峻
 * Creation date: 11-02-2006
 * 
 * XDoclet definition:
 * @struts.action path="/addOperator" name="addOperatorForm" input="/web/newOperator.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/web/saveInfo.jsp" redirect="true"
 */
public class AddOperatorAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddOperatorForm addOperatorForm = (AddOperatorForm) form;// TODO Auto-generated method stub
		Toperator operator=new Toperator();
		operator.setIsAdmin(Long.valueOf(addOperatorForm.getIsAdmin()));
		operator.setOperatorId(Long.valueOf(addOperatorForm.getOperatorId()));
		operator.setOperatorName(addOperatorForm.getOperatorName());
		operator.setOperatorPwd(addOperatorForm.getOperatorPwd());
		//在AddCustomerAction里有相关注释
		ApplicationContext context=new FileSystemXmlApplicationContext("C:\\eclipse\\workspace\\chinamobile\\src\\applicationContext.xml");
		IAdminOperator admin=(IAdminOperator)context.getBean("adminservice");
		//调用业务层方法增加操作员
		String message=admin.addOperator(operator);
		System.out.println(message);
		if(!message.equals("")){
			request.setAttribute("message", message);
			return mapping.findForward("success");
		}else{
			return mapping.getInputForward();
		}
	}
}