/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.FileSystemXmlApplicationContext;

import business.IOperator;

import po.*;
import struts.form.AddUserForm;

/** 
 * 功能:增加手机用户
 * 作者:赵昌峻
 * Creation date: 11-03-2006
 * 
 * XDoclet definition:
 * @struts.action path="/addUser" name="addUserForm" input="/web/newUser.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/web/saveInfo.jsp" redirect="true"
 */
public class AddUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddUserForm addUserForm = (AddUserForm) form;// TODO Auto-generated method stub
		HttpSession session=request.getSession();
		Tcustomer customer=(Tcustomer)session.getAttribute("customer");
		session.removeAttribute("customer");
		//		在AddCustomerAction里有相关注释
		ApplicationContext context=new FileSystemXmlApplicationContext("C:\\eclipse\\workspace\\chinamobile\\src\\applicationContext.xml");
		IOperator dooperator=(IOperator)context.getBean("operatorservice");
		//		调用业务层的方法判断手机号是否可用
		Tmobiles mobile=dooperator.isMobileCanUse(addUserForm.getMobile());
		String message="";
		if(mobile!=null){//先判断手机号是否可用
			Tuser user=new Tuser();
			user.setComLevel(addUserForm.getComLevel());
			user.setRoamingStatus(addUserForm.getRoamingStatus());
			user.setTcustomer(customer);
			user.setTmobiles(mobile);
			message=dooperator.addUser(user);//调用业务层的方法增加手机用户
			request.setAttribute("message", message);
			return mapping.findForward("success");
		}else{
			message="添加用户失败!该手机号已被占用!";
			request.setAttribute("message", message);
			return mapping.getInputForward();
		}
	}
}